# Generated by Django 4.0.3 on 2022-03-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mydriver', models.CharField(max_length=500)),
                ('departure', models.IntegerField(blank=True, default=0)),
                ('dest_lat', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10)),
                ('dest_lon', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10)),
                ('match_time', models.FloatField(blank=True, default=0)),
                ('dest_name', models.CharField(blank=True, default='0', max_length=50)),
                ('status', models.CharField(blank=True, default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SessionId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessId', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500, unique=True)),
                ('job', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('status', models.CharField(blank=True, default='0', max_length=100)),
                ('position', models.IntegerField(blank=True, default=0)),
                ('myorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GGG_backend.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='mypassenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GGG_backend.passenger'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('status', models.CharField(blank=True, default='0', max_length=100)),
                ('position', models.IntegerField(blank=True, default=0)),
                ('myorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GGG_backend.order')),
            ],
        ),
    ]
