# Generated by Django 4.0.3 on 2022-03-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='destination',
        ),
        migrations.AddField(
            model_name='order',
            name='dest_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='dest_lon',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='match_time',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='poi',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='poi',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10),
        ),
    ]
