# Generated by Django 4.0.3 on 2022-04-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.FloatField(default=1649247768.7684004),
        ),
    ]
