# Generated by Django 4.0.3 on 2022-04-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='carcolor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='carinfo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='driver',
            name='carnum',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.BigIntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='driver',
            name='realname',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='score',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='passenger',
            name='phone',
            field=models.BigIntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='passenger',
            name='realname',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
