# Generated by Django 4.0.3 on 2022-04-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
