# Generated by Django 4.0.3 on 2022-04-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='origin_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='origin_lon',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='origin_name',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
