# Generated by Django 4.0.3 on 2022-04-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='product',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='product',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
