# Generated by Django 4.0.3 on 2022-04-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='passenger_path',
            field=models.TextField(blank=True, default=''),
        ),
    ]
