# Generated by Django 4.0.3 on 2022-04-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0002_alter_order_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.FloatField(default=1649256319.3820882),
        ),
    ]
