# Generated by Django 4.0.3 on 2022-04-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0002_order_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
