# Generated by Django 4.0.3 on 2022-04-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0002_order_origin_lat_order_origin_lon_order_origin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='product',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='passenger',
            name='product',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
