# Generated by Django 4.0.3 on 2022-04-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0002_alter_driver_product_alter_passenger_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='myorder_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
