# Generated by Django 4.0.3 on 2022-03-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0002_remove_driver_id_alter_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mypassenger',
            field=models.CharField(max_length=500),
        ),
    ]
