# Generated by Django 4.0.3 on 2022-04-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0002_order_order_path_order_passenger_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
