# Generated by Django 4.0.3 on 2022-04-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0002_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='myorder',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='myorder',
        ),
        migrations.AddField(
            model_name='driver',
            name='myorder_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='order',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passenger',
            name='myorder_id',
            field=models.IntegerField(default=-1),
        ),
    ]
