# Generated by Django 4.0.3 on 2022-04-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0002_alter_driver_product_alter_passenger_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('border', models.TextField()),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
