# Generated by Django 4.0.3 on 2022-03-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0003_alter_order_mypassenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='id',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='name',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
