# Generated by Django 4.0.3 on 2022-05-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0003_order_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='range',
            field=models.FloatField(blank=True, default=10),
        ),
    ]
