# Generated by Django 4.0.3 on 2022-03-30 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GGG_backend', '0004_remove_passenger_id_alter_passenger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='myorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GGG_backend.order'),
        ),
    ]
