# Generated by Django 4.0.3 on 2022-03-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionid',
            name='username',
            field=models.CharField(max_length=500),
        ),
    ]
