# Generated by Django 4.0.3 on 2022-03-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_sessionid_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionid',
            name='key',
        ),
        migrations.AlterField(
            model_name='sessionid',
            name='sessId',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sessionid',
            name='username',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
