# Generated by Django 4.0.3 on 2022-03-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_sessionid_key_alter_sessionid_sessid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='positionX',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='positionY',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='positionX',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='passenger',
            name='positionY',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='passenger',
            name='status',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivername', models.CharField(max_length=500)),
                ('departureX', models.FloatField(blank=True, default=0)),
                ('departureY', models.FloatField(blank=True, default=0)),
                ('destinationX', models.FloatField(blank=True, default=0)),
                ('destinationY', models.FloatField(blank=True, default=0)),
                ('status', models.CharField(blank=True, default='0', max_length=10)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.passenger')),
            ],
        ),
    ]
