# Generated by Django 4.0.3 on 2022-03-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_driver_positionx_driver_positiony_driver_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X_axis', models.FloatField(blank=True, default=0)),
                ('Y_axis', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='drivername',
            new_name='driver',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='positionX',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='positionY',
        ),
        migrations.RemoveField(
            model_name='order',
            name='departureX',
        ),
        migrations.RemoveField(
            model_name='order',
            name='departureY',
        ),
        migrations.RemoveField(
            model_name='order',
            name='destinationX',
        ),
        migrations.RemoveField(
            model_name='order',
            name='destinationY',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='positionX',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='positionY',
        ),
        migrations.AddField(
            model_name='driver',
            name='position',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='departure',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='passenger',
            name='position',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
